name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

pool:
  name: 'AWS-ECS'


stages:

  - stage: build
    displayName: Build and Test
    jobs:
      - job: build
        displayName: Build and Test
        timeoutInMinutes: 40

        pool:
          name: 'AWS-ECS'

        workspace:
          clean: all

        steps:
          - checkout: self

          - bash: |
              instance_id="$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
              echo instance-id: "${instance_id}"
              echo connect to: https://eu-west-2.console.aws.amazon.com/systems-manager/session-manager/${instance_id}
              echo sudo su - ubuntu
              echo working directory: $(System.DefaultWorkingDirectory)
            displayName: Print AWS info

          - template: components/aws-assume-role.yml
            parameters:
              role: "auto-ops"
              profile: "apm_ptl"
              aws_account: "ptl"
            displayName: Assume AWS role

          - task: UsePythonVersion@0
            displayName: "Use Python 3.8"
            inputs:
              versionSpec: "3.8"

          - task: NodeTool@0
            displayName: "Use Node 13"
            inputs:
              versionSpec: '13.x'

          - task: s3-cache-action@0
            inputs:
              key: '"node modules" | s3CacheTask/node_modules'
              location: 's3CacheTask/node_modules'
              bucket: $(PIPELINE_CACHE_BUCKET)
            displayName: Cache node dependencies to s3

          - bash: make install-node
            condition: ne(variables.CACHE_RESTORED, 'true')
            displayName: Install node dependencies

          - bash: make install-poetry
            displayName: Install poetry dependencies

          - bash: |
              make test
              exit_code=$?
              echo Exit code - ${exit_code}
              make down
              exit ${exit_code}
            displayName: Run s3 tests
