version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4666
    healthcheck:
      test: ["CMD-SHELL", "awslocal s3 ls"]
      interval: 3s
      timeout: 10s
    ports:
      - '4666:4666'

  dependent_service:
    image: localstack/localstack:latest
    depends_on:
      localstack:
        condition: service_healthy
    # Additional configuration for dependent_service
