version: '3.6'  # Ensure the version is compatible with your Docker version

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4666
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]  # Updated to use CMD array format
      interval: 3s
      timeout: 10s
      retries: 3  # Optional: Add retries for better health check reliability
    ports:
      - '4666:4666'

