version: '3.6'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4666
    healthcheck:
      test: awslocal s3 ls
      interval: 3s
      timeout: 10s
    ports:
      - '4666:4666'
