version: '3.6'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    environment:
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4566
    ports:
      - '4566:4566'
      - '8080:8080'
