SHELL := /bin/bash
####################################################################################################
##
## Make for managing s3 Cache Action extension
##
####################################################################################################

install:
	npm install

test:
	npm test

test-watch:
	npm run test-watch

test-verbose:
	npm run test-verbose
